spring.application.name=Adapter
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
spring.kafka.consumer.group-id=adapter-group-1
spring.kafka.consumer.listener-id=adapter-listener-
tcp.server.port=9293
server.port=${METRICS_PORT:8180}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always