services:
  datahub-app:
    image: docker.io/fcabalo/datahub-app:latest
    container_name: datahub-app
    ports:
      - 8080:8080
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - LOG_PATH=/usr/logs
      - LOG_FILENAME=datahub
    volumes:
      - ./../logs:/usr/logs
      - ./../data:/usr/data

  adapter-1:
    image: docker.io/fcabalo/adapter-app:latest
    container_name: adapter-app-1
    ports:
      - 9293:9293
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - LOG_PATH=/usr/logs
      - LOG_FILENAME=adapter_1
    volumes:
      - ./../logs:/usr/logs
      - ./../data:/usr/data

  adapter-2:
    image: docker.io/fcabalo/adapter-app:latest
    container_name: adapter-app-2
    ports:
      - 9294:9293
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - LOG_PATH=/usr/logs
      - LOG_FILENAME=adapter_2
    volumes:
      - ./../logs:/usr/logs
      - ./../data:/usr/data