# prometheus.yml
global:
  scrape_interval: 15s  # How often Prometheus will scrape targets

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['broker:9404']
    scheme: http
      
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']