{
 "title": "Datahub Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Processed Message Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ingester_message_incoming_count_total",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ingester_time_seconds_max", "legendFormat": "ingester_max" },
    {
     "expr": "ingester_time_seconds_sum/ingester_time_seconds_count",
     "legendFormat": "ingester_average"
    },
    {
     "expr": "datahub_routing_time_seconds_max",
     "legendFormat": "routing_max"
    },
    {
     "expr": "datahub_routing_time_seconds_sum/datahub_routing_time_seconds_count",
     "legendFormat": "ingester_average"
    },
    {
     "expr": "datahub_conversion_time_seconds_max",
     "legendFormat": "conversion_max"
    },
    {
     "expr": "datahub_conversion_time_seconds_sum/datahub_conversion_time_seconds_count",
     "legendFormat": "conversion_average"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "adapter_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adapter_message_sent_count_total",
     "legendFormat": "PI {{partner_interface_id}}"
    }
   ]
  }
 ]
}