{
 "title": "Kafka Messages",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "incoming_grouping", "label": "Group By", "query": "source, messageType" }
  ]
 },
 "panels": [
  {
   "title": "Bytes In Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{topic=~\"(PI.(Incoming|Outgoing))|IncomingTopic\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Messages Rate (Message/Sec over 1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"PI3Incoming|PI6Incoming\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{topic=~\"(PI.(Incoming|Outgoing))|IncomingTopic\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Messages Rate (Message/sec Over 1min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{topic=~\"PI2Outgoing|PI4Outgoing|PI5Outgoing|PI7Outgoing\"}[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Message Source",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{topic=~\"PI3Incoming|PI6Incoming\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}