spring.application.name=datahubPOC
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9092}
spring.kafka.stream.app-id=stream-processor
spring.kafka.consumer.group-id=stream-processor
server.port=${SERVER_PORT:8080}

kafka.topic.incoming=IncomingTopic

data.source.path=${DATASOURCE_PATH:./../data/}
data.source.partner=partners.json
data.source.partnerInterface=partnerInterfaces.json
data.source.routingCriteria=routingCriteria.json

management.endpoints.web.exposure.include=*
management.endpoints.jmx.exposure.include=*
management.prometheus.metrics.export.enabled=true
management.observations.annotations.enabled=true
management.endpoint.health.show-details=always