FROM docker.io/amazoncorretto:21-alpine
ARG JAR_FILE=target/*.jar
WORKDIR /usr/Datahub
COPY ./target/Adapter-0.0.1-SNAPSHOT.jar /usr/Datahub/Adapter-0.0.1-SNAPSHOT.jar
RUN apk add --no-cache tzdata
EXPOSE 9293
ENTRYPOINT ["java","-jar","/usr/Datahub/Adapter-0.0.1-SNAPSHOT.jar"]
