FROM docker.io/amazoncorretto:21-alpine
ARG JAR_FILE=target/*.jar
WORKDIR /usr/Datahub
COPY ./target/DatahubPOC-0.0.1-SNAPSHOT.jar /usr/Datahub/DatahubPOC-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/Datahub/DatahubPOC-0.0.1-SNAPSHOT.jar"]
